name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libusb-dev
      run: sudo apt-get install libusb-1.0-0-dev xdotool -y
    - name: make
      run: make
